### ISSUE TITLE
Improve Download Page UI

### ISSUE THREAD

**Issue by Greatgabbar** [Greatgabbar/vithack#10]
I have use materialize css

**Comment by kevinngth** [comment]
Hi, I think you should include the public folder so that we can see what CSS and JS have been done so far. After doing that you can assign it to me

**Comment by Greatgabbar** [comment]
Sure bro ,
I assigned to u

**Comment by Greatgabbar** [comment]
any updates @kevinngth ?

**Comment by kevinngth** [comment]
just saw this, thanks! will start working on it

**Comment by tusharck** [comment]
I can also work on this if required.

**Comment by Greatgabbar** [comment]
yaa sure u can improve more

**Comment by tusharck** [comment]
Sure, will work on it.

**Comment by kevinngth** [comment]
> Sure, will work on it.

you can pull the changes where I refactored the view files so that it's easier to work with. Enjoy!

**Comment by tusharck** [comment]
> > Sure, will work on it.
> 
> you can pull the changes where I refactored the view files so that it's easier to work with. Enjoy!

Thanks.

**Comment by tusharck** [comment]
@Greatgabbar , I made the PR for this, can you please see. https://github.com/Greatgabbar/vithack/pull/16

**Comment by Greatgabbar** [comment]
@tusharck i see it there are two issues
1. The website is not responsive PS: looking good on desktop view
2. And on button(id="proceed")  eventListner is not working

**Comment by tusharck** [comment]
> @tusharck i see it there are two issues
> 
> 1. The website is not responsive PS: looking good on desktop view
> 2. And on button(id="proceed")  eventListner is not working

Hey @Greatgabbar , I guess i missed something, i added in the code. Might have been some error from my side, ill fix it.
Sorry for the trouble.
