### ISSUE TITLE
Download all file in a zip folder

### ISSUE THREAD

**Issue by Greatgabbar** [Greatgabbar/vithack#13]
Instead of downloading file one by one just click on download all and it will convert all files into zip and download it

**Comment by kartikagarwal9** [comment]
I want to contribute but did not understand the problem @Greatgabbar

**Comment by Greatgabbar** [comment]
yaa sure ,
basically it is a Certificate Generator
In which user upload csv and template of certificate
and then select the area on the template where here he/she want to add data like Name , Position etc
and after that we will give them the certificates
and there are two option to download the certificate 
1. they can download by downloading each certificate 
OR
2. they can download it by just clicking download all and then they get zip file in which they have their certificate
i want the implementaion of 2nd part

**Comment by Greatgabbar** [comment]
> I want to contribute but did not understand the problem @Greatgabbar

yaa sure ,
basically it is a Certificate Generator
In which user upload csv and template of certificate
and then select the area on the template where here he/she want to add data like Name , Position etc
and after that we will give them the certificates
and there are two option to download the certificate

1. they can download by downloading each certificate
OR
2. they can download it by just clicking download all and then they get zip file in which they have their certificate
i want the implementaion of 2nd part
@kartikagarwal9

**Comment by Greatgabbar** [comment]
GG
