### ISSUE TITLE
Needed a good readme file

### ISSUE THREAD

**Issue by Greatgabbar** [Greatgabbar/vithack#6]

**Comment by TiagoSansao** [comment]
Hey bro, I don't know what exactly your project is about, do you wanna me to make the base and you can put the text your want? @Greatgabbar

**Comment by Greatgabbar** [comment]
yaa sure ,
basically it is a Certificate Generator
In which user upload csv and template of certificate
and then select the area on the template where here he/she want to add data like Name , Position etc
and after that we will give them the certificates 
and no. of certificate is equal to no. of entry in csv file

**Comment by TiagoSansao** [comment]
Ok, I made a pull request with a base #7
There isn't content about your project, just the base to you put the texts. There are some comments telling how to put your information in each topic in a stylized way.
Good luck 😃

**Comment by Greatgabbar** [comment]
GG bro
